---
- name: Create the management tenant network for generator
  openstack.cloud.network:
    state: present
    cloud: "{{ cloud_detail }}"
    name: "{{ item.network_name }}"
    project: "{{ project_id }}"
    external: "{{ item.external }}"
    shared: "{{ item.shared }}"
  when:
    - admin
    - item.physical_network is not defined

- name: Create the management network for generator
  openstack.cloud.network:
    state: present
    cloud: "{{ cloud_detail }}"
    name: "{{ item.network_name }}"
    project: "{{ project_id }}"
    provider_physical_network: "{{ item.physical_network | default(omit) }}"
    provider_network_type: "{{ item.network_type | default(omit) }}"
    provider_segmentation_id: "{{ item.segmentation_id | default(omit) | int }}"
    external: "{{ item.external }}"
    shared: "{{ item.shared }}"
  when:
    - admin
    - item.physical_network is defined