---
- name: Run NFVbench role
  block:
    - name: Check if extra vars file exists
      stat:
        path: "{{ lookup('env', 'extra_vars') }}"
      register: extra_vars
      ignore_errors: true
      no_log: true
    - name: Load extra_vars
      include_vars: "{{ lookup('env', 'extra_vars') }}"
      when:
        - extra_vars.stat.exists
      no_log: true
    - name: Check user is admin
      openstack.cloud.identity_user_info:
        cloud: "{{ cloud_detail }}"
        validate_certs: "{{ validate_certs }}"
      register: user_info
      ignore_errors: true
      no_log: true
    - name: Register admin status
      set_fact:
        admin: False
      when:
        - user_info is failed
    - include_tasks: create_tenant.yml
      when: deploy | bool
    - include_tasks: generate_user_creds.yml
    - include_tasks: create_flavor.yml
      with_items: "{{ flavors }}"
      when:
        - admin | bool
        - deploy | bool
    - include_tasks: security_group.yml
      when:
        - deploy | bool
        - security_group_name is defined
        - security_group_name
    - include_tasks: create_management_network.yml
      with_items: "{{ management_networks }}"
      when:
        - deploy | bool
        - management_networks is defined
    - include_tasks: create_subnet.yml
      with_items: "{{ management_networks }}"
      when:
        - deploy | bool
        - management_networks is defined
    - include_tasks: create_port.yml
      with_items: "{{ management_networks }}"
      when:
        - deploy | bool
        - item.port_name is defined
    - include_tasks: create_loopvm_network.yml
      with_items: "{{ loop_vm_networks }}"
      when:
        - deploy | bool
        - loop_vm_networks is defined
    - include_tasks: create_subnet.yml
      with_items: "{{ loop_vm_networks }}"
      when:
        - deploy | bool
        - loop_vm_networks is defined
    - include_tasks: create_generator_network.yml
      with_together:
        - "{{ generator_networks }}"
        - "{{ e2e_vlans }}"
      when:
        - deploy | bool
        - item.0.topology is defined
        - item.0.topology == 'e2e' or item.0.topology == 'loopback_e2e'
    - include_tasks: create_generator_network.yml
      with_together:
        - "{{ generator_networks }}"
        - "{{ loopback_vlans }}"
      when:
        - deploy | bool
        - item.0.topology is defined
        - item.0.topology == 'loopback'
    - include_tasks: create_subnet.yml
      with_items: "{{ generator_networks }}"
      when: deploy | bool
    - include_tasks: create_port.yml
      with_items: "{{ generator_networks }}"
      when: deploy | bool
    - include_tasks: create_router.yml
      when: deploy | bool
    - include_tasks: create_config.yml
      when: deploy | bool
    - include_tasks: upload_image.yml
      when: deploy | bool
    - include_tasks: create_server.yml
      when: deploy | bool
    - include_tasks: healthcheck.yml
      when: deploy | bool or run_test | bool
    - include_tasks: run_test.yml
      when: run_test | bool
  always:
    - include_tasks: cleanup.yml
      when: cleanup | bool
